name: Cypress Test
on: [push]
jobs:
  cypress-run:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.0
       - name: Cypress.io
         uses: cypress-io/github-action@fd50b628255d62107377b511f928e6ebec975179
         with:
        #install-command: npm install
          start: npm start
        
